import { NextResponse } from "next/server";

const newsData = [
  {
    id: 1,
    date: "2026.01.22",
    title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    slug: "lorem-ipsum-dolor-sit-amet-consectetur-adipiscing-elit",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem illum quas hic esse quam laborum, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque!",
  },
  {
    id: 2,
    date: "2026.01.18",
    title: "Lorem ipsum dolor sit amet, sed do eiusmod tempor",
    slug: "lorem-ipsum-dolor-sit-amet-sed-do-eiusmod-tempor",
    content:
      "Lorem ipsum dolor sit amet, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem illum quas hic esse quam laborum, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque!",
  },
  {
    id: 3,
    date: "2026.01.10",
    title: "Lorem ipsum dolor sit amet, ut labore et dolore",
    slug: "lorem-ipsum-dolor-sit-amet-ut-labore-et-dolore",
    content:
      "Lorem ipsum dolor sit amet, ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem illum quas hic esse quam laborum, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet, ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 4,
    date: "2025.12.28",
    title: "Lorem ipsum dolor sit amet, quis nostrud exercitation",
    slug: "lorem-ipsum-dolor-sit-amet-quis-nostrud-exercitation",
    content:
      "Lorem ipsum dolor sit amet quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem illum quas hic esse quam laborum, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 5,
    date: "2025.12.20",
    title: "Lorem ipsum dolor sit amet, duis aute irure dolor",
    slug: "lorem-ipsum-dolor-sit-amet-duis-aute-irure-dolor",
    content:
      "Lorem ipsum dolor sit amet duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem illum quas hic esse quam laborum, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 6,
    date: "2025.12.12",
    title: "Lorem ipsum dolor sit amet, ex ea commodo consequat",
    slug: "lorem-ipsum-dolor-sit-amet-ex-ea-commodo-consequat",
    content:
      "Lorem ipsum dolor sit amet ex ea commodo conseguat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem illum quas hic esse quam laborum, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 7,
    date: "2025.12.12",
    title:
      "Lorem ipsum dolor sit amet consectetur, qui distinctio rem iusto ipsa modi cum",
    slug: "lorem-ipsum-dolor-sit-amet-consectetur-qui-distinctio-rem-iusto-ipsa-modi-cum",
    content:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque!",
  },
  {
    id: 8,
    date: "2025.12.10",
    title:
      "Lorem ipsum dolor sit amet, commodi minima corrupti quisquam architecto dignissimos",
    slug: "lorem-ipsum-dolor-sit-amet-commodi-minima-corrupti-quisquam-architecto-dignissimos",
    content:
      "Lorem ipsum dolor sit amet, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque!",
  },
  {
    id: 9,
    date: "2025.08.25",
    title: "Lorem ipsum dolor sit amet, amet tempore ab praesentium unde",
    slug: "lorem-ipsum-dolor-sit-amet-amet-tempore-ab-presentium-unde",
    content:
      "Lorem ipsum dolor sit amet, amet tempore ab praesentium unde? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque!",
  },
  {
    id: 10,
    date: "2025.08.17",
    title:
      "Lorem ipsum dolor sit amet doloremque illo ex natus sunt sed aliquid",
    slug: "lorem-ipsum-dolor-sit-amet-doloremque-illo-ex-natus-sunt-sed-alquid",
    content:
      "Lorem ipsum dolor sit amet, doloremque illo ex natus sunt sed aliquid? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque!",
  },
  {
    id: 11,
    date: "2025.07.14",
    title:
      "Lorem ipsum dolor sit amet laborum perspiciatis, nihil, nam commodi autem recusandae quam explicabo",
    slug: "lorem-ipsum-dolor-sit-amet-laborum-perspiciatis-nihil-nam-commodi-autem-recusandae-quam-explicabo",
    content:
      "Lorem ipsum dolor sit amet, laborum perspiciatis, nihil, nam commodi autem recusandae quam explicabo? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque!",
  },
  {
    id: 12,
    date: "2025.12.13",
    title: "Lorem ipsum dolor sit amet, rem illum quas hic esse quam laborum",
    slug: "lorem-ipsum-dolor-sit-amet-rem-illum-quas-hic-esse-quam-laborum",
    content:
      "Lorem ipsum dolor sit amet, rem illum quas hic esse quam laborum? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque!",
  },
  {
    id: 13,
    date: "2025.05.07",
    title:
      "Lorem ipsum dolor sit amet dignissimos cupiditate reiciendis officiis suscipit",
    slug: "lorem-ipsum-dolor-sit-amet-dignissimos-cupiditate-reiciendis-officiis-suscipit",
    content:
      "Lorem ipsum dolor sit amet, dignissimos cupiditate reiciendis officiis suscipit? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque!",
  },
  {
    id: 14,
    date: "2026.05.04",
    title: "Lorem ipsum dolor sit amet veritatis consectetur aspernatur minima",
    slug: "lorem-ipsum-dolor-sit-amet-veritatis-consectetur-aspernatur-minima",
    content:
      "Lorem ipsum dolor sit amet, veritatis consectetur aspernatur minima? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque!",
  },
  {
    id: 15,
    date: "2025.03.13",
    title:
      "Lorem ipsum dolor sit amet, culpa voluptas repudiandae corporis provident",
    slug: "lorem-ipsum-dolor-sit-amet-culpa-voluptas-repudiandae-corporis-provident",
    content:
      "Lorem ipsum dolor sit amet, culpa voluptas repudiandae corporis provident? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque!",
  },
  {
    id: 16,
    date: "2025.05.16",
    title:
      "Lorem ipsum dolor sit amet, voluptate nemo dolore temporibus debitis",
    slug: "lorem-ipsum-dolor-sit-amet-voluptate-nemo-dolore-temporibus-debitis",
    constent:
      "Lorem ipsum dolor sit amet, voluptate nemo dolore temporibus debitis? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque!",
  },
  {
    id: 17,
    date: "2026.09.15",
    title:
      "Lorem ipsum dolor sit amet tempora quos excepturi, est eligendi animi accusantium, culpa voluptast",
    slug: "lorem-ipsum-dolor-sit-amet-tempora-quos-excepturi-est-eligendi-animi-accusantium-culpa-voluptas",
    content:
      "Lorem ipsum dolor sit amet, tempora quos excepturi, est eligendi animi accusantium, culpa voluptas? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque!",
  },
  {
    id: 18,
    date: "2026.07.28",
    title:
      "Lorem ipsum dolor sit amet, nihil distinctio unde ipsa, id non labore",
    slug: "lorem-ipsum-dolor-sit-amet-nihil-distinctio-unde-ipsa-id-non-labore",
    content:
      "Lorem ipsum dolor sit amet, nihil distinctio unde ipsa, id non labore? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque!",
  },
  {
    id: 19,
    date: "2026.04.23",
    title: "Lorem ipsum dolor sit amet magni aspernatur nam impedit excepturi",
    slug: "lorem-ipsum-dolor-sit-amet-magni-aspernatur-nam-impedit-excepturi",
    content:
      "Lorem ipsum dolor sit amet, magni aspernatur nam impedit excepturi? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque!",
  },
  {
    id: 20,
    date: "2025.02.13",
    title:
      "Lorem ipsum dolor sit amet ratione quia, ducimus optio a accusamus dicta iure magni autem",
    slug: "lorem-ipsum-dolor-sit-amet-ratione-quia-ducimus-optio-a-accusamus-dicta-iure-magni-autem",
    content:
      "Lorem ipsum dolor sit amet, ratione quia, ducimus optio a accusamus dicta iure magni autem? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui distinctio rem iusto ipsa modi cumque, voluptate nemo dolore temporibus debitis, commodi minima corrupti quisquam architecto dignissimos? Voluptas, doloremque!",
  },
];

export async function GET() {
  return NextResponse.json(newsData);
}
